### ISSUE TITLE
Some questions about this study

### ISSUE THREAD

**Issue by METQL** [weiyu123112/City-Metro-Network-Expansion-with-RL#1]
Dear Wei Yu:
I have read your article, but there are some questions that are not clear. Can you help me to answer them?
1. In Section 4.1, you defined the status as the selected site sequence st=(z1,z2,...,zt-1), but why use all the site information st = {Xt0,Xt1, . . . ,Xtn2−1} as the real-time status in Section 4.3?
2. How to embed the location of a specific site z_{t-1} extracted from CNN? What does L_ z_ {t-1},: and L_i mean?
I'm looking forward to your reply. 
Thank you very much!

**Comment by weiyu123112** [comment]
Dear Friend:

Thank you for your attention to our work. Here, I will try my best to answer your questions.

For the first question, the selected site sequence st=(z1,z2,...,zt-1) in Section 4.1 is the essence of our state, and all the site information st = {Xt0,Xt1, . . . ,Xtn2−1} in Section 4.3 is actually a general representation for the state in Section 4.1. The neural network takes the fixed dimension data as input, so only the selected site sequence of varying length may not be an appropriate representation for the input. As a result, we represent the state as the form in Section 4.3.

For the second question, consider two tensors, one of which is for the location feature and the other is the station selection feature. The two CNNs are used to embed these two tensors respectively, as shown in Figure 2.
The  L_ z_ {t-1},:  is the embedding vector of the z_ {t-1}, corresponding to the z_ {t-1}th column of the matrix L.
L_i is the two-dimensional coordinates of station i in the grid space, such as (0,0).

Yours faithfully.

**Comment by METQL** [comment]
![PZ48E5L4){}ZRNT}0G9YHFN](https://user-images.githubusercontent.com/46370810/112497428-8f290700-8dc0-11eb-963b-1ef327ed2a1a.png)
Thank you very much for your answer, but I still have some doubts.
1. If l_i is a two-dimensional coordinate of site i in grid space, then l_1, l_2..., l_ {n2-1}, that is, {(0,0), (0,1)...,(29,29)}, can such coordinates be directly input into CNN? 
2. Each time when the next site is selected, the location information of all grids needs to be input, and the coordinate representation of the position information of each grid is fixed. Does that mean that each input {l_1,l_2...
, L_ {n2-1}} are all the same (I.e. {(0,0), (0,1)...,(29,29)})?
3. In addition, how can the vector matrix processed by CNN determine that column z_ {t-1} (row) represents the characteristic representation of site z_ {t-1}?
I am looking forward to your reply. 
Thank you very much again.

**Comment by weiyu123112** [comment]
1. Yes, such coordinates can be directly input into CNN. Notice the ‘class Encoder(nn.Module)’ in the file metro_model.py. For these information, you can think of it as a 2 * 841 tensor input to the CNN, in which 841=29*29.
2. Please notice that the {(0,0), (0,1)...,(29,29)} is the location feature which is fixed, but our inputs also include the station selection feature which changes with each step of the agent.
3. For this question, please also pay attention to the ‘class Encoder(nn.Module)’ in the file metro_model.py. Its output size is (batch, hidden_size, 29*29).

**Comment by METQL** [comment]
OK, I think I understood. Thank you very much for your creative work and your patient answer.
